# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08wc.proto\x12\x02wc\"0\n\x0c\x43ountRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\"3\n\nCountReply\x12\x12\n\nword_count\x18\x01 \x01(\x03\x12\x11\n\tserver_id\x18\x02 \x01(\t2B\n\x10WordCountService\x12.\n\nCountWords\x12\x10.wc.CountRequest\x1a\x0e.wc.CountReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COUNTREQUEST']._serialized_start=16
  _globals['_COUNTREQUEST']._serialized_end=64
  _globals['_COUNTREPLY']._serialized_start=66
  _globals['_COUNTREPLY']._serialized_end=117
  _globals['_WORDCOUNTSERVICE']._serialized_start=119
  _globals['_WORDCOUNTSERVICE']._serialized_end=185
# @@protoc_insertion_point(module_scope)
